language: node_js
node_js:
  - '22'

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npx playwright install --with-deps chromium

script:
  - npm run lint
  - npm run format:check
  - npm test
  - npm run build
  - npm run e2e

after_success:
  - firebase use default
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
